blog/user/routes.py
from flask import abort
from flask import send_from_directory
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_user, login_required
from blog import db, bcrypt
from blog.models import User, UserFile, UserFileAccess, Notification, UserFile_2
from blog.user.digital_signature import sign, PUBLIC_KEY, SECRET_KEY
from blog.user.forms import Registrationform, LoginForm, FileUploadForm
from werkzeug.utils import secure_filename
import os
import mimetypes
users = Blueprint('users', __name__)


@users.route("/sign", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.blog"))
    form = Registrationform()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Ваш аккаунт был создан.")
        return redirect(url_for('users.login'))
    return render_template("sign.html", form = form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.account'))
    return render_template("login.html", form = form)
UPLOAD_FOLDER = r"C:\Users\Vlad12005\PycharmProjects\university_2\blog\uploads"
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif',"doc","docx","json"}
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS



@users.route("/downolads_2", methods=['GET', 'POST'])
@login_required
def downolads_2():
    form = FileUploadForm()
    form.users.choices = [(user.id, user.username) for user in User.query.all() if user.id != current_user.id]

    if request.method == 'POST' and form.validate_on_submit():
        file = request.files.get('file')
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            save_path = os.path.join(UPLOAD_FOLDER, filename)
            file.save(save_path)

            user_file_2 = UserFile_2(
                filename=filename,
                file_path=save_path,
                user_id=current_user.id,
                is_public=form.is_public.data
            )
            db.session.add(user_file_2)
            db.session.commit()

            if not form.is_public.data:
                for user_id in form.users.data:
                    db.session.add(UserFileAccess(file_id=user_file_2.id, user_id=user_id))
                db.session.commit()

            return redirect(url_for('users.account'))

    return render_template("Download documents.html", form=form)



@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    notifications = Notification.query.filter_by(user_id=current_user.id).order_by(Notification.created_at.desc()).all()
    return render_template("account.html", notifications=notifications)
@users.route("/downoloads", methods=['GET', 'POST'])
@login_required
def downoloads():
    form = FileUploadForm()
    form.users.choices = [(user.id, user.username) for user in User.query.all() if user.id != current_user.id]

    if request.method == 'POST' and form.validate_on_submit():
        file = request.files.get('file')
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            save_path = os.path.join(UPLOAD_FOLDER, filename)
            file.save(save_path)

            user_file = UserFile(
                filename=filename,
                file_path=save_path,
                user_id=current_user.id,
                is_public=form.is_public.data
            )
            db.session.add(user_file)
            db.session.commit()

            if form.is_public.data:
                for user in User.query.all():
                    if user.id != current_user.id:
                        db.session.add(Notification(
                            user_id=user.id,
                            from_user_id=current_user.id,
                            message=f'{current_user.username}Вам предоставлен доступ к файлу  "{filename}"',
                            type='file'
                        ))
            else:

                for user_id in form.users.data:
                    db.session.add(UserFileAccess(file_id=user_file.id, user_id=user_id))
                    db.session.add(Notification(
                        user_id=user_id,
                        from_user_id=current_user.id,
                        message=f'Вам предоставлен доступ к файлу "{filename}".',
                        type='file'
                    ))

            db.session.commit()
            flash("Файл успешно загружен и доступ предоставлен.", "success")
            return redirect(url_for('users.account'))

    return render_template("downloads.html", form=form)
@users.route('/uploads/<filename>')
@login_required
def uploaded_file(filename):
    file = UserFile.query.filter_by(filename=filename).first()
    if not file:
        abort(404)

    if file.user_id != current_user.id and current_user not in file.accessible_users:
        abort(403)

    directory = os.path.dirname(file.file_path)
    filename_safe = os.path.basename(file.file_path)

    mime_type, _ = mimetypes.guess_type(filename_safe)
    if not mime_type:
        mime_type = 'application/octet-stream'

    return send_from_directory(directory, filename_safe, mimetype=mime_type)


@users.route("/all_files", methods=['GET', 'POST'])
@login_required
def all_files():
    files = UserFile.query.filter(
        UserFile.accessible_users.any(id=current_user.id)
    ).all()

    message = None

    if request.method == 'POST':

        if 'sign_file_id' in request.form:
            file_id = int(request.form['sign_file_id'])
            file_to_sign = UserFile.query.get_or_404(file_id)

            if file_to_sign.user_id != current_user.id and current_user not in file_to_sign.accessible_users:
                abort(403)

            if file_to_sign.signature:
                message = "Файл уже подписан."
            else:
                signature = sign(PUBLIC_KEY, SECRET_KEY)
                file_to_sign.signature = signature
                db.session.commit()
                if file_to_sign.user_id != current_user.id:
                    notification = Notification(
                        user_id=file_to_sign.user_id,
                        from_user_id=current_user.id,
                        message=f'Пользователь {current_user.username} подписал ваш файл "{file_to_sign.filename}".',
                        type='file_signed'
                    )
                    db.session.add(notification)
                    db.session.commit()



    return render_template("all_documents.html", files=files, message=message)


@users.route("/mark_read/<int:notification_id>", methods=['POST'])
@login_required
def mark_notification_read(notification_id):
    notification = Notification.query.get_or_404(notification_id)

    if notification.user_id != current_user.id:
        abort(403)

    notification.status = 'read'
    db.session.commit()

    if notification.type == 'file' and notification.from_user_id:

        all_users = User.query.filter(User.id != current_user.id).all()
        for user in all_users:
            db.session.add(Notification(
                user_id=user.id,
                from_user_id=current_user.id,
                message=f'Пользователь {current_user.username} получил файл.',
                type='info'
            ))
        db.session.commit()

    flash("Уведомление отмечено как прочитанное.", "success")
    return redirect(url_for('users.account'))


@users.route("/help")
@login_required
def help_page():
    return render_template("help.html")

@users.route("/all_uploaded_files")
@login_required
def all_uploaded_files():
    files = UserFile.query.filter_by(user_id=current_user.id).all()
    files_2 = UserFile_2.query.filter_by(user_id=current_user.id).all()
    return render_template("all_uploaded_files.html", files=files, files_2=files_2)

blog/templates/Download documents.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='downloads.css') }}">
</head>
<body>
<div class="top-bar">
    <div class="logo">Cli/WEB-приложение для документооборота</div>
    <div class="nav-buttons">
        <a href="{{ url_for('users.downoloads')}}">
    <button  type="button" class="btn btn-primary">Загрузить документ на подпись</button>
    </a>
        <a href="{{ url_for('users.downolads_2')}}">
    <button  type="button" class="btn btn-primary">Загрузить документ </button>
    </a>
        <a href="{{ url_for('users.account')}}">
    <button  type="button" class="btn btn-primary">Профиль</button>
    </a>
        <a href="{{ url_for('users.all_files')}}">
        <button onclick="">Список документов на подпись</button>
        </a>
        <a href="{{ url_for('users.all_uploaded_files')}}">
        <button onclick="">Список всех загруженных документов</button>
        </a>
    </div>
</div>

 <div class="login">
     <div class="login-screen">
         <h2>Загрузить документ</h2>
         <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.file.label(class="form-control-label") }}
            {{ form.file(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.users.label(class="form-control-label") }}

            {{ form.users(class="form-control", multiple=True) }}
        </div>
        <div class="form-group">
            {{ form.is_public.label(class="form-control-label") }}
            {{ form.is_public() }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
     </div>
</div>
 <script>
    document.addEventListener('keydown', function(event) {
        if (event.key.toLowerCase() === 'h' && !['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) {
            window.location.href = "/help";
        }
    });
    </script>
</body>
</html>

blog/templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пример</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='account.css') }}">
</head>
<body>
<div class="top-bar">
    <div class="logo">Cli/WEB-приложение для документооборота</div>
    <div class="nav-buttons">
<a href="{{ url_for('users.downoloads')}}">
    <button  type="button" class="btn btn-primary">Загрузить документ на подпись</button>
    </a>
        <a href="{{ url_for('users.downolads_2')}}">
    <button  type="button" class="btn btn-primary">Загрузить документ </button>
    </a>
        <a href="{{ url_for('users.account')}}">
    <button  type="button" class="btn btn-primary">Профиль</button>
    </a>
        <a href="{{ url_for('users.all_files')}}">
        <button onclick="">Список документов на подпись</button>
        </a>
        <a href="{{ url_for('users.all_uploaded_files')}}">
        <button onclick="">Список всех загруженных документов</button>
        </a>
    </div>
</div>
 <div class="login">
     <div class="login-screen">
     <h1>
     {{ current_user.username }}</h1>
    <p>Рады видить вас на нашем сайте</p>
         <p>Ваши уведомления</p>
<ul class="list-group mb-4">
    {% for n in notifications %}
        <li class="list-group-item d-flex justify-content-between align-items-center
            {% if n.status == 'unread' %}list-group-item-warning{% else %}list-group-item-light{% endif %}">
            <div>
                <strong>{{ n.sender.username }}</strong>: {{ n.message }}<br>
            </div>
            {% if n.status == 'unread' %}
                <form method="POST" action="{{ url_for('users.mark_notification_read', notification_id=n.id) }}">
                    <button type="submit" class="btn btn-sm btn-outline-success">Прочитано</button>
                </form>
            {% else %}
                <span class="badge badge-success">Прочитано</span>
            {% endif %}
        </li>
    {% else %}
        <li class="list-group-item">Нет уведомлений.</li>
    {% endfor %}
</ul>
     <ul>
{% for n in unread_notifications %}
    <li>
        {{ n.message }} — от {{ n.sender.username }} |
        <form method="POST" action="{{ url_for('users.mark_notification_read', notification_id=n.id) }}" style="display:inline;">
            <button type="submit">Прочитано</button>
        </form>
    </li>
{% endfor %}
</ul>




     </div>
</div>

 <script>
    document.addEventListener('keydown', function(event) {
        if (event.key.toLowerCase() === 'h' && !['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) {
            window.location.href = "/help";
        }
    });
    </script>




</body>
</html>

blog/templates/all_documents.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='all_documents.html.css') }}">
</head>
</head>
<body>


<div class="top-bar">
    <div class="logo">Cli/WEB-приложение для документооборота</div>
    <div class="nav-buttons">
    <a href="{{ url_for('users.downolads')}}">
    <button  type="button" class="btn btn-primary">Загрузить документ</button>
    </a>
        <a href="{{ url_for('users.account')}}">
    <button  type="button" class="btn btn-primary">Профиль</button>
    </a>

    </div>

        </div>
</div>
<div class="login">
     <div class="login-screen">
 <h1>Все загруженные файлы</h1>
  <ul>
    {% for file in files %}
      <li>
        <a href="{{ url_for('users.uploaded_file', filename=file.filename) }}">
          {{ file.filename }}
        </a> - Загружено пользователем: {{ file.user.username }} ({{ file.upload_time.strftime('%Y-%m-%d %H:%M:%S') }})
      </li>
    {% endfor %}
  </ul>







     </div>
</div>
</body>
</html>

blog/templates/all_uploaded_files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='account.css') }}">
</head>
<body>
<div class="top-bar">
    <div class="logo">Cli/WEB-приложение для документооборота</div>
    <div class="nav-buttons">
    <a href="{{ url_for('users.downoloads')}}">
    <button  type="button" class="btn btn-primary">Загрузить документ на подпись</button>
    </a>
        <a href="{{ url_for('users.downolads_2')}}">
    <button  type="button" class="btn btn-primary">Загрузить документ </button>
    </a>
        <a href="{{ url_for('users.account')}}">
    <button  type="button" class="btn btn-primary">Профиль</button>
    </a>
        <a href="{{ url_for('users.all_files')}}">
        <button onclick="">Список документов на подпись</button>
        </a>
        <a href="{{ url_for('users.all_uploaded_files')}}">
        <button onclick="">Список всех загруженных документов </button>
        </a>
    </div>

        </div>
<div class="login">
     <div class="login-screen">
     <h1>Все загруженные документы </h1>
         <ul>
  {% for file in files %}
    <li>{{ file.filename }}</li>
  {% endfor %}
</ul>

<ul>
  {% for file in files_2 %}
    <li>{{ file.filename }}</li>

  {% endfor %}
</ul>

     </div>
</div>
 <script>
    document.addEventListener('keydown', function(event) {
        if (event.key.toLowerCase() === 'h' && !['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) {
            window.location.href = "/help";
        }
    });
    </script>
</body>
</html>

blog/templates/downloads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='downloads.css') }}">
</head>
<body>
<div class="top-bar">
    <div class="logo">Cli/WEB-приложение для документооборота</div>
    <div class="nav-buttons">
         <a href="{{ url_for('users.account')}}">
    <button  type="button" class="btn btn-primary">Профиль</button>
    </a>
        <button onclick="">Выйти</button>
    </div>
</div>

 <div class="login">
     <div class="login-screen">
         <h2>Загрузить файл</h2>
            <h2>Загрузить файл</h2>
         <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.file.label(class="form-control-label") }}
            {{ form.file(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.users.label(class="form-control-label") }}
            <!-- Важно: атрибут multiple=True, чтобы поддерживать множественный выбор -->
            {{ form.users(class="form-control", multiple=True) }}
        </div>
        <div class="form-group">
            {{ form.is_public.label(class="form-control-label") }}
            {{ form.is_public() }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
     </div>
</div>
</body>
</html>

blog/templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пример</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='first.css') }}">
</head>
<body>
  <div class="login">
    <div class="login-screen">
      <div class="app-title">
        <h1>Аккаунт</h1>
      </div>

      <div class="login-form">
           <a href="{{ url_for('users.register') }}"> <button type="button" class="btn btn-primary  ">Зарегестрироваться</button></a>
           <a href="{{ url_for('users.login') }}"> <button type="button" class="btn btn-primary btn-large btn-block">Войти</button></a>

      </div>
    </div>
  </div>
</body>

blog/templates/help.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Справка | Документооборот</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 2rem;
            background-color: #f8f9fa;
        }
        h1, h2 {
            color: #343a40;
        }
        ul {
            margin-bottom: 2rem;
        }
        li {
            margin-bottom: 0.5rem;
        }
        code {
            background-color: #e9ecef;
            padding: 2px 6px;
            border-radius: 4px;
        }
    </style>
</head>
<body>

    <h1>Справка по приложению документооборота</h1>

    <h2>1. Управление аккаунтом</h2>
    <ul>
        <li> Регистрация с созданием уникальной учетной записи.</li>
        <li> Вход с использованием имени пользователя и пароля.</li>
        <li> Безопасность: пароли хранятся в зашифрованном виде (hash).</li>
    </ul>

    <h2>2. Работа с документами</h2>
    <ul>
        <li> Загрузка любых типов документов: <code>.doc</code>, <code>.docx</code>, <code>.txt</code>, <code>.json</code> и др.</li>
        <li> Выбор пользователей, которым будет предоставлен доступ к документу.</li>
        <li> Уведомление пользователей о новом документе, доступном для подписи.</li>
        <li>✍ Подпись документов с фиксацией факта подписи.</li>
        <li> Уведомление владельца документа о подписи другим пользователем.</li>
    </ul>

    <h2>3. Просмотр документов</h2>
    <ul>
        <li> Просмотр списка всех загруженных документов.</li>
        <li> Просмотр документов, ожидающих подписи.</li>
    </ul>

    <h2>4. Команда помощи</h2>
    <ul>
        <li> Используйте команду <code>-h</code> или откройте эту страницу, чтобы получить справку по работе с системой.</li>
    </ul>


</body>
</html>

blog/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пример</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
</head>
<body>
 <div class="login">
    <div class="login-screen">
      <div class="app-title">
       <div class="login-form">

  <form method="post">
  <h2>Войти</h2>
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-control-label") }}
      {{ form.username(class="form-control form-control-lg") }}
      {% if form.username.errors %}
        <ul class="errors">
          {% for error in form.username.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.password.label(class="form-control-label") }}
      {{ form.password(class="form-control form-control-lg") }}
      {% if form.password.errors %}
        <ul class="errors">
          {% for error in form.password.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Войти</button>
  <p>Нет аккаунта?</p> <a class='ml-2'   href="{{ url_for('users.register')}}">Зарегистрироваться</a>
  </form>

       </div>
      </div>
    </div>
 </div>
</body>
</html>

blog/templates/sign.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пример</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='sign.css') }}">
</head>
<body>
  <div class="login">
    <div class="login-screen">
      <div class="app-title">
       <div class="login-form">
  <form method="post">
    {{ form.hidden_tag() }}
<h3>Регистрация</h3>
    <div class="form-group">
      {{ form.username.label(class="form-control-label") }}
      {{ form.username(class="form-control form-control-lg") }}
      {% if form.username.errors %}
        <ul class="errors">
          {% for error in form.username.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>

    <div class="form-group">
      {{ form.password.label(class="form-control-label") }}
      {{ form.password(class="form-control form-control-lg") }}
      {% if form.password.errors %}
        <ul class="errors">
          {% for error in form.password.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
  <div class="form-group">
      {{ form.confirn_password.label(class="form-control-label") }}
      {{ form.confirn_password(class="form-control form-control-lg") }}
      {% if form.confirn_password.errors %}
        <ul class="errors">
          {% for error in form.confirn_password.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>

    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
  </form>
       </div>
</div>
    </div>
  </div>
</body>